[toolchain]
package_manager = "yarn"
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vectaiproj = "ETe5hWKprkrRVBryrhvPVDPS37ea4U9iZ7p6pv78Kusf"
parity_swap = "Gf8A8CSDftRjWCjiJPPWoM6ugnW639F78M7mwWQf2u9Q"
mock_swap = "31JXctg1sE4KsKobegoWmTMcRWCbVGRZv7N58w8MFDwJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/mainnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.spec.ts\""
